apiVersion: apps/v1
kind: Deployment
metadata:
  name: berry-admin-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: berry-admin-ui
  template:
    metadata:
      labels:
        app: berry-admin-ui
    spec:
      containers:
        - name: my-app-container
          image: tasmidur/berry-admin-ui-image:master-f7448bc1a1d3b83faa16eadecdbfbbed840c1e0d
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
