apiVersion: v1 
kind: Service
metadata:
  name: berry-admin-ui-service
  namespace: default
spec:
  selector:
    app: berry-admin-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
  type: NodePort
